package kelolapengeluaran;

import java.sql.SQLException;
import kelolapengeluaran.dao.UserDAO;
import kelolapengeluaran.config.Config;

/**
 *
 * @author Lenovo
 */
public class FormRegister extends javax.swing.JFrame {
    private final UserDAO userDAO;

    /** Creates new form RegisterForm */
    public FormRegister() {
        initComponents();
        try {
            userDAO = new UserDAO(Config.configDB());
        } catch (SQLException e) {
            throw new RuntimeException("Error initializing user data access object", e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldUsername = new javax.swing.JTextField();
        LabelUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        PasswordFieldPassword = new javax.swing.JPasswordField();
        ButtonRegister = new javax.swing.JButton();
        LinkLabelToLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextFieldUsername.setToolTipText("Input Username");
        TextFieldUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldUsername.setName("username"); // NOI18N

        LabelUsername.setText("Username");
        LabelUsername.setName("usernameLabel"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRASI");

        LabelNama.setText("Nama");
        LabelNama.setToolTipText("Nama");
        LabelNama.setName("namaLabel"); // NOI18N

        TextFieldNama.setToolTipText("Nama");
        TextFieldNama.setName("nama"); // NOI18N
        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });

        LabelPassword.setText("Password");
        LabelPassword.setName("passwordLabel"); // NOI18N

        PasswordFieldPassword.setToolTipText("Input Password");
        PasswordFieldPassword.setName("password"); // NOI18N

        ButtonRegister.setBackground(new java.awt.Color(102, 102, 255));
        ButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegister.setText("Daftar");
        ButtonRegister.setAutoscrolls(true);
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });

        LinkLabelToLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LinkLabelToLogin.setText("Sudah punya akun? Login");
        LinkLabelToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkLabelToLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldUsername)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldNama)
                    .addComponent(PasswordFieldPassword)
                    .addComponent(ButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUsername)
                            .addComponent(LabelNama)
                            .addComponent(LabelPassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LinkLabelToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(LabelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkLabelToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        TextFieldUsername.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        String nama = TextFieldNama.getText();
        String username = TextFieldUsername.getText();
        String password = new String(PasswordFieldPassword.getPassword());
        
        if (nama.isEmpty() || username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Registrasi gagal. Pastikan kamu mengisi semua data yang diperlukan!.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Register user
            boolean success = userDAO.registerUser(username, password, nama);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Registrasi gagal, Coba lagi.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }   
        }
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void LinkLabelToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkLabelToLoginMouseClicked
        new KelolaPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LinkLabelToLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LinkLabelToLogin;
    private javax.swing.JPasswordField PasswordFieldPassword;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
